name: Fetch Ranking Scheduler

on:
  schedule:
    - cron: "39 16 * * 0"

jobs:
  fetch-ranking:
    name: Fetch Ranking
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm ci
    - run: "npm run fetch"

    - name: git setting
      run: |
        git config --local user.email "48653039+y-i-bot@users.noreply.github.com"
        git config --local user.name "y-i-bot"
    - name: Commit files
      run: |
        git pull
        git add ranking.json
        git commit -m "Update ranking.json"
        git push origin master
